spring.application.name=inventory-forecasting-system

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
spring.datasource.username=root
spring.datasource.password=vaibhav@12

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ML Forecast API URLs
ml.forecast.api.url=http://localhost:8000/predict
ml.forecast.batch.url=http://localhost:8000/predict/batch

# JWT Configuration
jwt.secret=InventoryForecastingSystemSecretKey2024VaibhavMCAProject
jwt.expiration=86400000

# Data.sql Configurations
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql